<?php

namespace Droid\Plugin\Fw\Generator;

use Droid\Model\Firewall;
use Droid\Model\Rule;

class UfwGenerator
{
    protected $firewall;
    
    public function __construct(Firewall $firewall)
    {
        $this->firewall = $firewall;
    }
    
    public function generate($hostname)
    {
        $o = '# Generated by Droid: ' . date('d/M/Y H:i') . "\n";
        $rules = $this->firewall->getRulesByHostname($hostname);
        
        $o .= "ufw --force reset\n";
        foreach ($rules as $rule) {
            $o .= $this->generateRule($rule);
        }
        return $o;
    }
    
    public function generateRule(Rule $rule)
    {
        $addresses = $this->firewall->constructAddresses($rule->getAddress());
        $o = '';
        foreach ($addresses as $address) {
            $o .= "ufw ";
            $o .= $rule->getAction() . ' ';
            $o .= 'from ' . $address . ' to any port ';
            $o .= $rule->getPort() . ' proto ' . $rule->getProtocol();
            $o .= ' # ' . $rule->getAddress();
            $o .= "\n";
        }
        return $o;
    }
    
}
